name: terraform-module-ci

on: workflow_call

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform fmt
        run: terraform fmt
      
      - name: Terraform validate
        run: |
          terraform init
          terraform validate
